# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
variables:
- name: BuildParameters.RestoreMVCSampleBuildProjects
  value: 'samples/ASP.NET MVC/AuthArmorSdk.Samples.ASP.NET-MVC/*.csproj'
- name: BuildParameters.RestoreSDKProjects
  value: 'src/AuthArmor.Sdk/*.csproj'

trigger:
- main
jobs:
- job: BuildMVCSample
  displayName: Build MVC Sample and Store Artifacts
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: $(BuildParameters.RestoreMVCSampleBuildProjects)
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: $(BuildParameters.RestoreMVCSampleBuildProjects)
        arguments: --configuration $(BuildConfiguration)
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/sample
    - task: PublishBuildArtifacts@1
      displayName: PublishArtifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'sample-drop'
        publishLocation: 'Container'

- job: BuildSDK
  displayName: Build SDK and Store Artifacts
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: $(BuildParameters.RestoreSDKProjects)
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: $(BuildParameters.RestoreSDKProjects)
        arguments: --configuration $(BuildConfiguration)
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/sdk
    - task: PublishBuildArtifacts@1
      displayName: PublishArtifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'sdk-drop'
        publishLocation: 'Container'
