# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
variables:

- name: BuildParameters.RestoreBuildProjects
  value: 'src/AuthArmor.Sdk/*.csproj'

trigger:
- main
jobs:
- job: BuildSDK
  displayName: Build SDK and Store Artifacts
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: $(BuildParameters.RestoreBuildProjects)
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: $(BuildParameters.RestoreBuildProjects)
        arguments: --configuration $(BuildConfiguration)
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      displayName: PublishArtifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
